spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bsn_db
    username: mohit
    password: mohit
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  mail:
    host: localhost
    port: 1025
    username: mohit
    password: mohit
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 2cb097b2a305d0047aed9af1015bb5542fbd6d16a40705bcd17048db9265060b
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    uploads:
      file-upload-path: "./uploads"

server:
  port: 8080
